basePath: /api/v1
host: localhost:8086
info:
  contact: {}
  description: Микросервис для управления сценариями автоматизации умного дома
  title: Automation Service API
  version: "1.0"
paths: {}
swagger: "2.0"
